//! A subscription sidecar that translatus starts, owns, and shuts down.
//!
//! The sidecar is how a Codex/Claude plan becomes an OpenAI-compatible
//! endpoint, and it shipped as homework: install Node dependencies by hand,
//! start a server by hand, copy the token it prints, paste it into Settings,
//! and keep the terminal open. Every one of those steps is something the
//! program already knows how to do — the kit rides along in the release
//! archive, the start command is fixed, and the token is generated by the
//! server itself.
//!
//! Leaving it manual cost more than convenience. The pasted token had to live
//! in the OS keychain, and reading it back from an ad-hoc-signed binary raises
//! an authorisation dialog that nobody can click in an agent session — so the
//! MCP path failed with 401 even after the user had configured everything
//! correctly. A sidecar owned by this process needs no keychain at all: the
//! token is generated here, handed to the child, and dies with it.

use anyhow::{anyhow, Context, Result};
use std::io::{BufRead, BufReader};
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::time::{Duration, Instant};

/// What a managed sidecar translates with when the caller named no model.
///
/// The sidecar serves whatever the user's plan serves; this is the current
/// generation and the same default the kit's own registry carries. Kept here
/// because the CLI has to choose before the sidecar exists to be asked.
pub const DEFAULT_MODEL: &str = "claude-sonnet-5";

pub struct Managed {
    child: Child,
    pub base_url: String,
    pub token: String,
}

impl Managed {
    /// Start a sidecar on a free loopback port with a fresh token.
    pub fn start(quiet: bool) -> Result<Self> {
        let dir = locate_kit(std::env::var_os("TRANSLATUS_SIDECAR_DIR").map(PathBuf::from))?;
        ensure_dependencies(&dir, quiet)?;

        let port = free_port()?;
        let token = fresh_token();
        let mut child = Command::new(node_bin())
            .arg("src/server.js")
            .current_dir(&dir)
            .env("LLM_SUB_KIT_PORT", port.to_string())
            .env("LLM_SUB_KIT_TOKEN", &token)
            // Book-length batches run for minutes; the default is a hang
            // detector, not a work limit.
            .env("LLM_SUB_KIT_REQUEST_TIMEOUT_MS", "600000")
            .stdout(Stdio::null())
            .stderr(Stdio::piped())
            .spawn()
            .with_context(|| format!("could not start the sidecar in {}", dir.display()))?;

        let base_url = format!("http://127.0.0.1:{port}/v1");
        match wait_until_healthy(port, Duration::from_secs(30)) {
            Ok(()) => Ok(Self {
                child,
                base_url,
                token,
            }),
            Err(e) => {
                // The child's stderr is the only place that says why.
                let why = child
                    .stderr
                    .take()
                    .map(|s| {
                        BufReader::new(s)
                            .lines()
                            .map_while(Result::ok)
                            .take(6)
                            .collect::<Vec<_>>()
                            .join("; ")
                    })
                    .unwrap_or_default();
                let _ = child.kill();
                Err(anyhow!(
                    "{e}{}",
                    if why.is_empty() {
                        String::new()
                    } else {
                        format!(" — {why}")
                    }
                ))
            }
        }
    }
}

impl Drop for Managed {
    fn drop(&mut self) {
        let _ = self.child.kill();
        let _ = self.child.wait();
    }
}

/// Where the sidecar lives, in the order the layouts actually occur.
///
/// The override arrives as an argument rather than being read here so the tests
/// never touch process-global environment: two tests mutating env from parallel
/// threads is a race that shows up as an unrelated test failing once in a while.
fn locate_kit(override_dir: Option<PathBuf>) -> Result<PathBuf> {
    let mut tried: Vec<PathBuf> = Vec::new();
    let check = |p: PathBuf, tried: &mut Vec<PathBuf>| -> Option<PathBuf> {
        if p.join("src/server.js").is_file() {
            Some(p)
        } else {
            tried.push(p);
            None
        }
    };

    if let Some(p) = override_dir {
        if let Some(found) = check(p.clone(), &mut tried) {
            return Ok(found);
        }
        return Err(anyhow!(
            "TRANSLATUS_SIDECAR_DIR points at {}, which has no src/server.js",
            p.display()
        ));
    }
    if let Ok(exe) = std::env::current_exe() {
        if let Some(bin) = exe.parent() {
            // Release archive: the binary and subscription-kit are siblings.
            if let Some(f) = check(bin.join("subscription-kit"), &mut tried) {
                return Ok(f);
            }
            // Homebrew: bin/translatus with the kit under libexec.
            if let Some(prefix) = bin.parent() {
                if let Some(f) = check(prefix.join("libexec/subscription-kit"), &mut tried) {
                    return Ok(f);
                }
            }
        }
    }
    // A source checkout, including `cargo run`.
    let mut here = std::env::current_dir().unwrap_or_default();
    loop {
        if let Some(f) = check(here.join("apps/subscription-kit"), &mut tried) {
            return Ok(f);
        }
        if !here.pop() {
            break;
        }
    }
    Err(anyhow!(
        "no subscription sidecar found (looked in: {}). It ships inside the release \
         archive as subscription-kit/; point TRANSLATUS_SIDECAR_DIR at it, or use \
         --provider openai with your own --base-url.",
        tried
            .iter()
            .map(|p| p.display().to_string())
            .collect::<Vec<_>>()
            .join(", ")
    ))
}

/// `npm install` on first use. The dependency tree is ~440 MB because the
/// vendor SDKs carry platform binaries, which is why it is fetched rather than
/// shipped: it would take the release archive from 4 MB to 150 MB.
fn ensure_dependencies(dir: &Path, quiet: bool) -> Result<()> {
    if dir.join("node_modules").is_dir() {
        return Ok(());
    }
    if !quiet {
        eprintln!("  preparing the subscription sidecar (one-time npm install)…");
    }
    let out = Command::new(npm_bin())
        .args(["install", "--omit=dev", "--no-audit", "--no-fund"])
        .current_dir(dir)
        .output()
        .with_context(|| {
            format!(
                "could not run npm in {} — the sidecar needs Node 20+ on PATH",
                dir.display()
            )
        })?;
    if !out.status.success() {
        return Err(anyhow!(
            "npm install failed in {}: {}",
            dir.display(),
            String::from_utf8_lossy(&out.stderr)
                .lines()
                .rev()
                .take(4)
                .collect::<Vec<_>>()
                .join("; ")
        ));
    }
    Ok(())
}

fn node_bin() -> String {
    std::env::var("TRANSLATUS_NODE").unwrap_or_else(|_| "node".into())
}

fn npm_bin() -> String {
    std::env::var("TRANSLATUS_NPM").unwrap_or_else(|_| "npm".into())
}

/// Ask the OS for a free loopback port, then let go of it. The gap before the
/// child binds is a race in principle; on loopback, for a port the OS just
/// declared free, it has never been the failure anyone hits.
fn free_port() -> Result<u16> {
    let l = std::net::TcpListener::bind("127.0.0.1:0")?;
    Ok(l.local_addr()?.port())
}

/// A per-run token. The kit requires at least 16 characters and it never
/// leaves this process tree.
fn fresh_token() -> String {
    use std::hash::{BuildHasher, Hasher, RandomState};
    let mut out = String::with_capacity(48);
    for _ in 0..3 {
        let mut h = RandomState::new().build_hasher();
        h.write_usize(std::process::id() as usize);
        h.write_u128(
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or_default(),
        );
        out.push_str(&format!("{:016x}", h.finish()));
    }
    out
}

fn wait_until_healthy(port: u16, timeout: Duration) -> Result<()> {
    let deadline = Instant::now() + timeout;
    let addr = format!("127.0.0.1:{port}");
    while Instant::now() < deadline {
        if std::net::TcpStream::connect_timeout(
            &addr.parse().expect("loopback addr"),
            Duration::from_millis(200),
        )
        .is_ok()
        {
            return Ok(());
        }
        std::thread::sleep(Duration::from_millis(150));
    }
    Err(anyhow!(
        "the sidecar did not start listening on {addr} within {}s",
        timeout.as_secs()
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_fresh_token_is_long_enough_and_not_repeated() {
        let a = fresh_token();
        let b = fresh_token();
        assert!(a.len() >= 16, "the kit rejects tokens under 16 chars: {a}");
        assert_ne!(a, b, "two runs must not share a token");
    }

    #[test]
    fn a_missing_kit_says_where_it_looked() {
        let dir = std::env::temp_dir().join("tx-no-kit-here");
        std::fs::create_dir_all(&dir).unwrap();
        let err = locate_kit(Some(dir.clone())).unwrap_err().to_string();
        assert!(err.contains("src/server.js"), "unhelpful: {err}");
        assert!(
            err.contains(&dir.display().to_string()),
            "must name the path: {err}"
        );
    }

    /// A real checkout resolves without any override — the layout the CLI
    /// actually ships in must be one of the ones it looks for.
    #[test]
    fn the_repo_layout_resolves() {
        // Only meaningful when run from the workspace; skip elsewhere.
        if std::path::Path::new("apps/subscription-kit/src/server.js").is_file() {
            assert!(locate_kit(None).is_ok());
        }
    }
}
